import { useEffect, useState } from 'react'
import './App.css'

type Page = 'home' | 'privacy' | 'terms' | 'support'
const links: { page: Page; label: string }[] = [
  { page: 'home', label: 'Home' }, { page: 'privacy', label: 'Privacy Policy' },
  { page: 'support', label: 'Support' },
]
const getPage = (): Page => { const page = window.location.hash.replace('#/', '') as Page; return links.some((link) => link.page === page) ? page : 'home' }

function Brand() { return <a className="brand" href="#/home" aria-label="Bic Reader home"><img src="/assets/Bicreaderlogo.png" alt="" /><span>Bic Reader</span></a> }

function HomePage() { return <main>
  <section className="hero-section"><div className="hero-copy"><span className="eyebrow">Read better. Remember more.</span><h1>Your reading, beautifully organized.</h1><p>Bic Reader gives you a calm, focused place to enjoy your books, save your progress, and keep every great idea close at hand.</p><div className="hero-actions"><a className="button button-secondary" href="#features">Explore features</a></div></div><div className="reader-preview"><div className="preview-toolbar"><img src="/assets/Bicreaderlogo.png" alt="" /><strong>My Library</strong><span>AR</span></div><div className="preview-body"><aside><i/><i/><i/><i/></aside><article><small>CHAPTER 04</small><h2>The quiet power of a good book</h2><p>Reading gives us somewhere to go when we have to stay where we are.</p><div className="text-lines"><i/><i/><i/><i/><i/></div><div className="progress"><span/></div><small>42% complete</small></article></div></div></section>
  <section className="features" id="features"><div className="section-heading"><span className="eyebrow">Made for readers</span><h2>Everything you need. Nothing you don't.</h2></div><div className="feature-grid"><article><span className="feature-icon">Aa</span><h3>Focused reading</h3><p>A clean, distraction-free reading experience that puts your book first.</p></article><article><span className="feature-icon">✓</span><h3>Always in sync</h3><p>Pick up exactly where you left off, whenever you're ready to read.</p></article><article><span className="feature-icon">✦</span><h3>Your own library</h3><p>Keep your collection organized and find your next read in seconds.</p></article></div></section>
</main> }

const policyContent: Record<'privacy', { eyebrow: string; title: string; intro: string; sections: [string, string][] }> = {
  privacy: { eyebrow: 'Your data matters', title: 'Privacy Policy', intro: 'We believe privacy should be simple and transparent. Here is what Bic Reader collects and how we use it.', sections: [
    ['Information we collect', 'We may collect account details such as your name, email address, account ID, and authentication information. PDFs stay on your device by default. If premium cloud sync is enabled, PDFs, filenames, highlights, notes, reading positions, timestamps, and reader settings may be uploaded to Supabase.'],
    ['AI reading assistant', 'When you use the AI assistant, your question and selected or extracted PDF text are sent through a Bic Reader Supabase Edge Function to OpenAI to generate a response. AI conversation history is stored locally on your device. Do not submit confidential or highly sensitive material unless you accept this processing.'],
    ['Purchases and diagnostics', 'Apple processes App Store payments. RevenueCat receives subscription and entitlement information so we can provide premium features. Sentry receives privacy-filtered crash and error information. We do not receive payment-card details or use your information for advertising tracking.'],
    ['How we use information', 'We use information to authenticate accounts, provide reading and sync features, process subscriptions, answer requested AI questions, support users, maintain reliability, prevent abuse, and comply with law. We do not sell personal information.'],
    ['Your choices and deletion', 'Cloud sync, social sign-in, and AI are optional. Delete your account from Profile → Delete account or contact support@bicreader.com. Account deletion removes associated cloud data where supported; offline PDFs may remain on your device until you remove them.'],
    ['Security and children', 'We use reasonable safeguards including authenticated access, private cloud storage, and row-level security. Bic Reader is intended for users aged 13 and older and is not directed to children under 13.'],
    ['Contact', 'For privacy questions or requests, email support@bicreader.com. Read the full policy source in the Bic Reader repository before publishing any changes.'],
  ] },
}

function PolicyPage({ type }: { type: 'privacy' }) { const content = policyContent[type]; return <main className="document-page"><header><span className="eyebrow">{content.eyebrow}</span><h1>{content.title}</h1><p>{content.intro}</p><small>Last updated: September 14, 2026</small></header><div className="document-content">{content.sections.map(([title, text], index) => <section key={title}><span>{String(index + 1).padStart(2, '0')}</span><div><h2>{title}</h2><p>{text}</p></div></section>)}</div></main> }
function SupportPage() { return <main className="support-page"><section className="support-intro"><span className="eyebrow">We're here to help</span><h1>How can we help?</h1><p>Have a question, found an issue, or want to share an idea? We'd love to hear from you.</p></section><section className="support-grid"><div className="contact-card"><span className="contact-icon">@</span><h2>Email support</h2><p>For general questions, account help, or feedback.</p><a href="mailto:support@bicreader.com">support@bicreader.com</a></div></section></main> }
function App() { const [page, setPage] = useState<Page>(getPage); const [menuOpen, setMenuOpen] = useState(false); useEffect(() => { const update = () => { setPage(getPage()); setMenuOpen(false); window.scrollTo(0, 0) }; window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update) }, []); return <div className="site-shell"><header className="navbar"><Brand /><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation" aria-expanded={menuOpen}><span/><span/><span/></button><nav className={menuOpen ? 'open' : ''}>{links.map((link) => <a key={link.page} className={page === link.page ? 'active' : ''} href={`#/${link.page}`}>{link.label}</a>)}</nav></header>{page === 'home' && <HomePage />}{page === 'privacy' && <PolicyPage type="privacy" />}{page === 'support' && <SupportPage />}<footer><Brand /><p>Thoughtful reading, every day.</p><span>© 2026 Bic Reader</span></footer></div> }
export default App
